Models/Domain/BlogPost.cs
namespace Blogie.Web.Models.Domain
{
    public class BlogPost
    {
        public Guid Id { get; set; }
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string Content  { get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public DateTime PublishedDate { get; set; }
        public  string Author{ get; set; }
        public bool Visible { get; set; }
        public ICollection<Tag> Tags { get; set; }

    }
}

Models/Domain/Tag.cs
namespace Blogie.Web.Models.Domain
{
    public class Tag
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string DisplayName{ get; set; }
        public ICollection<BlogPost> BlogPosts{ get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Blogie.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ViewModels/AddTagRequest.cs
namespace Blogie.Web.Models.ViewModels
{
    public class AddTagRequest
    {
        public string Name { get; set; }
        public string DisplayName{ get; set; }

    }
}

Controllers/AdminTagController.cs
using Blogie.Web.Data;
using Blogie.Web.Models.Domain;
using Blogie.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Blogie.Web.Controllers
{
    public class AdminTagController : Controller
    {
        private BlogieDBContext _blogieDbContext;
        public AdminTagController(BlogieDBContext blogieDBContext)
        {
            _blogieDbContext = blogieDBContext;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public IActionResult Add(AddTagRequest addTagRequest)
        {
            //var name = Request.Form["name"];
            //var displayName= Request.Form["displayName"];

            //var name = addTagRequest.Name;
            //var displayName = addTagRequest.DisplayName;
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName,
            };
            _blogieDbContext.Add(tag);
            _blogieDbContext.SaveChanges();
            return View("Add");
        }
        [HttpGet]
        public ActionResult List()
        {
            var tags = _blogieDbContext.Tags.ToList();
            return View(tags);
        }
    }
}

Controllers/HomeController.cs
using Blogie.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Blogie.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/AdminTag/Add.cshtml
@model Blogie.Web.Models.ViewModels.AddTagRequest
@{

}
<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>
            Add New Tag - Admin Functionality
        </h1>
    </div>
</div>
<div class="container py-5">
    <form method="post">
        <div>
            <label class="form-label" >Name</label>
            <input type="text" class="form-control" id="name" name="name" asp-for="Name" />
        </div>
        <div>
            <label class="form-label">DisplayName</label>
            <input type="text" class="form-control" id="displayname" name="displayName" asp-for="DisplayName"/>
        </div>
        <di>
            <button type="submit" class="btn btn-dark mt-2"> Submmit </button>
        </di>
    </form>
</div>

Views/AdminTag/List.cshtml
@model List<Blogie.Web.Models.Domain.Tag>
@{
}
<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>
            List All Tags- Admin Functionality
        </h1>
    </div>
</div>

<div class="container py-5">
    @if (Model != null && Model.Any())
    {
        <table class="table table-dark table-striped table-hover">
            <thead>
                <tr>Id</tr>
                <tr>Name</tr>
                <tr>Display</tr>
            </thead>
            <tbody>
                @foreach (var tag in Model)
                {
                <th>tag.Id</th>
                <th>tag.Name</th>
                <th>tag.Display</th>
                }
            </tbody>
        </table>
    }
    else
    {
       <h1>There is no spoon</h1> 
    }

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blogie.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Blogie.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark text-light  border-bottom box-shadow ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blogie.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 text-light">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin Panel
                            </button>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="Add Tag" asp-controller="AdminTag" asp-area="" asp-action="Add">Add Tag</a></li>
                            </ul>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div>
            &copy; 2023 - Blogie.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>